version: "3.9"
services:
  bot:
    build: .
    restart: always
    volumes:
      - ./peewee.db:/usr/src/app/peewee.db
    environment:
      - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
      - TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET
      - TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET
      - TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY
